### ISSUE TITLE
{"Object reference not set to an instance of an object."}

### ISSUE THREAD

**Issue by MonsterMMORPG** [vrvis/aardvark.semantictextonforests#2]
I tried both debug and regular version x64 for visual studio 2013

Here my test and train files txt.

test : http://sta.sh/0c7y35hn82h

train : http://sta.sh/0139tzctti6r

here the error how can i solve?

I checked and it loads fine into          LibSvm.Problem train

![tried both](https://cloud.githubusercontent.com/assets/4149474/10440774/e720f302-714a-11e5-8cb3-a25df0cfe6f8.png)

   at Cache.lru_delete(Cache\* , head_t\* h) in c:\data\development\aardvark.semantictextonforests\src\libsvm\svm.cpp:line 114
   at Cache.get_data(Cache\* , Int32 index, Single*\* data, Int32 len) in c:\data\development\aardvark.semantictextonforests\src\libsvm\svm.cpp:line 130
   at SVC_Q.get_Q(SVC_Q\* , Int32 i, Int32 len) in c:\data\development\aardvark.semantictextonforests\src\libsvm\svm.cpp:line 1284
   at Solver.Solve(Solver\* , Int32 l, QMatrix\* Q, Double\* p_, SByte\* y_, Double\* alpha_, Double Cp, Double Cn, Double eps, SolutionInfo\* si, Int32 shrinking) in c:\data\development\aardvark.semantictextonforests\src\libsvm\svm.cpp:line 595
   at ?A0x8d29d844.solve_c_svc(svm_problem\* prob, svm_parameter\* param, Double\* alpha, SolutionInfo\* si, Double Cp, Double Cn) in c:\data\development\aardvark.semantictextonforests\src\libsvm\svm.cpp:line 1460
   at ?A0x8d29d844.svm_train_one(svm_problem\* prob, svm_parameter\* param, Double Cp, Double Cn) in c:\data\development\aardvark.semantictextonforests\src\libsvm\svm.cpp:line 1657
   at svm_train(svm_problem\* prob, svm_parameter\* param) in c:\data\development\aardvark.semantictextonforests\src\libsvm\svm.cpp:line 2218
   at LibSvm.Svm.Train(Problem problem, Parameter parameter) in c:\data\development\aardvark.semantictextonforests\src\libsvm\libsvm.clr.h:line 342
   at libsvmdeneme.MainWindow.Button_Click(Object sender, RoutedEventArgs e) in c:\Users\King\Documents\Visual Studio 2013\Projects\libsvmdeneme\libsvmdeneme\MainWindow.xaml.cs:line 44
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run()
   at libsvmdeneme.App.Main() in c:\Users\King\Documents\Visual Studio 2013\Projects\libsvmdeneme\libsvmdeneme\obj\x64\Debug\App.g.cs:line 0
   at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
   at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by aszabo314** [comment]
Greetings,

The problem you are having is with libsvm itself, not our wrapper. It is due to badly configured parameters. Please note that you have to fully describe all parameters needed for the model you are using, as described in the official documentation (https://www.csie.ntu.edu.tw/~cjlin/libsvm/). A fully described parameter set could look like so:

``` c#
            var param = new LibSvm.Parameter()
            {
                C = 1,
                Gamma = 1,
                KernelType = LibSvm.KernelType.POLY,
                SvmType = LibSvm.SvmType.C_SVC,
                Coef0 = 0,
                Degree = 0,
                Nu = 0.0,
                CacheSize = 100,
                Eps = 1e-3,
                p = 0.1,
                Shrinking = 1,
                Probability = 0,
                WeightLabel = new int[0],
                Weight = new double[0]
            };
```

In particular, you were missing the `Eps` parameter, which is used as a termination condition of the algorithm, and can vary depending on your own data sets. Your code runs on our end after the parameter is defined. Read up on the different type of SVM classifiers to see which parameters you need to define (https://en.wikipedia.org/wiki/Support_vector_machine).

Furthermore, the rest of our syntax reads exactly like that of libsvm (i.e. for cross validation, select the parameters you want to try out and check each accuracy by counting the positives). Use the references provided on the official site for more examples.

Regards.

**Comment by MonsterMMORPG** [comment]
Ty for reply however you put a wrapper and by default it is not working. Does that make sense? i did not change anything. Anyway i managed to make LibSVMsharp work with 64bit :)
